Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,41 +8,41 @@ jobs:
           pip install -r requirements.txt
           python manage.py check
 
-  test:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run: |
-          pip install -r requirements.txt
-          python manage.py test taskManager
+test:
+  docker:
+    - image: python:3.6
+  steps:
+    - checkout
+    - run: |
+        pip install -r requirements.txt
+        python manage.py test taskManager
 
-   release:
-    machine: true                                        # What is this for?
-    steps:
-      - checkout
-      - run: |
-          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
-          docker build -t $DOCKER_USERNAME/django.nv .   # Build the application into Docker image
-          docker push $DOCKER_USERNAME/django.nv         # Push the image into registry
+release:
+  machine: true                                        # What is this for?
+  steps:
+    - checkout
+    - run: |
+        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
+        docker build -t $DOCKER_USERNAME/django.nv .   # Build the application into Docker image
+        docker push $DOCKER_USERNAME/django.nv         # Push the image into registry
 
-  integration:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run:
-          command: |
-            echo "This is an integration step"
-            # exit 1
-          when: always                    # Even if the job fails, continue to the next stages
+integration:
+  docker:
+    - image: python:3.6
+  steps:
+    - checkout
+    - run:
+        command: |
+          echo "This is an integration step"
+          # exit 1
+        when: always                    # Even if the job fails, continue to the next stages
 
-  prod:
-    docker:
-      - image: python:3.6
-    steps:
-      - checkout
-      - run: echo "This is a 'deploy' step."
+prod:
+  docker:
+    - image: python:3.6
+  steps:
+    - checkout
+    - run: echo "This is a 'deploy' step."
 
 workflows:
   version: 2
